#!/bin/bash -e

RELAYER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
RELAYER_CONF="$HOME/.relayer"
GAIA_CONF="$(pwd)/data"
CONFIG_DATA="$(pwd)/data"

# Ensure user understands what will be deleted
if ([[ -d $RELAYER_CONF ]] || [[ -d $GAIA_CONF ]]) && [[ ! "$1" == "skip" ]]; then
  read -p "$0 will delete \$HOME/.relayer and \$(pwd)/data folder. Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

cd $RELAYER_DIR
rm -rf $RELAYER_CONF &> /dev/null
pwd
bash scripts/three-chainz "skip"

echo "waiting for blocks..."
sleep 5

rly tx link demo -d -o 3s --home $CONFIG_DATA/rly-0
rly tx link demo2 -d -o 3s --home $CONFIG_DATA/rly-1
#go run main.go tx transfer ibc-0 ibc-1 1000samoleans $(go run main.go ch addr ibc-1)
#go run main.go tx transfer ibc-1 ibc-2 1000samoleans $(go run main.go ch addr ibc-2)
#go run main.go tx transfer ibc-2 ibc-1 1000samoleans $(go run main.go ch addr ibc-1)
#go run main.go tx transfer ibc-1 ibc-0 1000samoleans $(go run main.go ch addr ibc-0)
#sleep 2
#go run main.go tx relay-packets demo -d
#sleep 2
#go run main.go tx relay-acknowledgements demo -d